services:
  temperaturemonitor.api:
    image: temperaturemonitor.api
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      GIN_MODE: release

