services:
  temperaturemonitor.api:
    image: temperaturemonitor.api
    build:
      context: api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      GIN_MODE: release
    volumes:
      - ./db/:/app/db/
  temperaturemonitor.grafana:
    image: grafana/grafana:12.0.1
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PLUGINS_PREINSTALL=yesoreyeram-infinity-datasource
      - INFINITY_URL=http://temperaturemonitor.api:8080
    volumes:
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: {}
